In [ ]:
import pandas as pd
path="/content/IMDB Dataset.csv"


In [ ]:
#df=pd.read_csv("/content/IMDB Dataset.csv")
df = pd.read_csv("/content/IMDB Dataset.csv", escapechar="\\")

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

vect=CountVectorizer()
docs=np.array(['I am studying in Mits',
               'please provide a good internship opportunity',
               'thanks for all the support'])

bag=vect.fit_transform(docs)

In [ ]:
print(vect.vocabulary_)

{'am': 1, 'studying': 10, 'in': 4, 'mits': 6, 'please': 8, 'provide': 9, 'good': 3, 'internship': 5, 'opportunity': 7, 'thanks': 12, 'for': 2, 'all': 0, 'the': 13, 'support': 11}


In [ ]:
print(bag.toarray())

[[0 1 0 0 1 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 1 1 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 1 1 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
np.set_printoptions(precision=2)
tfidf=TfidfTransformer(use_idf=True,norm='l2',smooth_idf=True)
print(tfidf.fit_transform(bag).toarray())

[[0.   0.5  0.   0.   0.5  0.   0.5  0.   0.   0.   0.5  0.   0.   0.  ]
 [0.   0.   0.   0.45 0.   0.45 0.   0.45 0.45 0.45 0.   0.   0.   0.  ]
 [0.45 0.   0.45 0.   0.   0.   0.   0.   0.   0.   0.   0.45 0.45 0.45]]


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(
    use_idf=True,
    norm='l2',
    smooth_idf=True)

y=df.sentiment.values
x=tfidf.fit_transform(df['review'].values.astype('U'))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.5,shuffle=False)

In [ ]:
import pickle
from sklearn.linear_model import LogisticRegressionCV
clf=LogisticRegressionCV(cv=5,
                         scoring='accuracy',
                         random_state=0,
                         n_jobs=-1,
                         verbose=3,
                         max_iter=300).fit(x_train,y_train)
saved_model=open('saved_model.sav','wb')
pickle.dump(clf,saved_model)
saved_model.close()

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  4.7min finished


In [ ]:
filename='saved_model.sav'
saved_clf=pickle.load(open(filename,'rb'))
saved_clf.score(x_test,y_test)

0.8972